### ISSUE TITLE
about Molformer

### ISSUE THREAD

**Issue by JWSunny** [smiles724/3D-Transformer#2]
hello, thanks for your harding work, i am reading your new work about Molformer project. But i can not get the project at https://github.com/smiles724/Molformer.

**Comment by smiles724** [comment]
Thanks for your attention. We are still striving on polishing our project. For instance, we extract motifs not only from small molecules but also proteins. The version you saw in Openreview is only a draft for rebuttal, where only motifs in small molecules are considered. We plan to submit our new work to ICML 2022 after revision, and the code will release after our submission.
